### ISSUE TITLE
Ignore comment lines

### ISSUE THREAD

**Issue by edg2s** [ExplodingCabbage/sublime-gitignorer#10]
Ignore files can contain comments starting with '#' which should be ignored.

**Comment by edg2s** [comment]
Confused with functionality in another git plugin.

**Comment by ExplodingCabbage** [comment]
Yeah, I thought when I saw this in my inbox that it couldn't possible make sense since this plugin doesn't parse .gitignore - it asks Git to tell it which files are ignored, *precisely* so that I can't fuck things like this up. :)
