### ISSUE TITLE
Files are still ignored after package removal

### ISSUE THREAD

**Issue by anoduck** [ExplodingCabbage/sublime-gitignorer#27]
I installed the package to try it out, after I discovered that this was clearly not in the best interests of developing my application I removed it and updated my sublime configuration, and they are still being ignored. I did remove them from the excluded patters/excluded files/excluded folder setting in my sublime config json file.  They are still being ignored and there is virtually no change in how Sublime Text is behaving while the plugin was installed, and after it is uninstalled. My files are still being ignored.

What would occur to make this change appear to be a permanent fixture in my Sublime Setup? It has added considerable time to my development process.

**Comment by neandrake** [comment]
@anoduck this happens because the plugin effectively generates configurations that it puts into your settings file. You can undo the changes it made but opening your preferences/settings file and removing or updating the preferences with "exclude..." etc. in them. This resolved the issue for me.

**Comment by anoduck** [comment]
@neandrake Thanks! I will give it a try.
